### ISSUE TITLE
use localStorage for saving colour

### ISSUE THREAD

**Issue by AryanShinde** [AryanShinde/ColorPalette#11]

**Comment by satyamgupta1495** [comment]
Hey Aryan, I'd like to work on this!

**Comment by doctype-Melvin** [comment]
I think this issue is already resolved. Palettes are stored in localStorage when clicking save.

**Comment by satyamgupta1495** [comment]
> I think this issue is already resolved. Palettes are stored in localStorage when clicking save.

Just noticed that!

**Comment by VarunGujarathi2001** [comment]
i'd like to contribute

**Comment by AryanShinde** [comment]
Sorry guys, Thanks for the Contribution! Cheers!
